server:
  port: 7003

spring:
    cloud:
      discovery:
        enabled: true
    application:
      name: BILLING-PAYMENT
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/billing_payment_hackthon?createDatabaseIfNotExist=true&useSSL=true 
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: examly
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      userMangementServiceCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 12
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

user-management-service:
  base-url: http://USER-MANAGEMENT