server:
  port: 7003

spring:
    application:
      name: BILLING-PAYMENT
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/billing_payment_kackthon?createDatabaseIfNotExist=true&useSSL=true 
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: examly
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: dialect=org.hibernate.dialect.MySQL5Dialect
                
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost